config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  get 'pages/home'

  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true, length: {maximum: 55}
  belongs_to :user
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  validates :brand_id, presence: true
  validates :name, presence: true 
  validates :description, presence: true
  validates :price, presence: true, length: {maximum: 100}
  validates :name, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :brands, dependent: :destroy
  has_many :products, dependent: :destroy
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_brand, only:[:edit, :update, :show, :destroy]
  
  
  def index
    @brands = Brand.all
  end
  
  def show
  end
  
  def new
  @brand = Brand.new
  end
  
  def edit
  end
  
  def create
  @brand = current_user.brands.new(set_brand)
  if @brand.save
    flash[:notice] = "Brand was successfully created"
    redirect_to brand_path (@brand)
  else
    render 'new'
  end
  
  def update
  if @brand.update(set_brand)
    flash[:notice] = "Brand was successfully updated"
    redirect_to brand_path(@brand)
  else
    render 'edit'
  end
end
  
  def destroy
    if @brand.destroy
      flash[:notice] = "Brand #{@brand.name}, was successfully destroyed"
      redirect_to brands_path
    end
  end
end
  
  
  
  
  
  
  
  
  private 
  def find_brand
    @brand = Brand.find(params[:id])
  end
  
  def set_brand
    params.require(:brand).permit(:name, :brand_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if current_user
      redirect_to brands_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only:[:edit, :update, :show, :destroy]
  
  def index
   @products = current_user.products.all
  end
  
  def show
  end
  
  def new
    @product = Product.new
  end
  
  def edit
  end
  
  def create
  @product = current_user.products.new(set_product)
  if @product.save
    flash[:notice] = "Product was successfully reated"
    redirect_to products_path(@product)
  else
    render 'new'
  end
end

  def update
    if @product.update(set_product)
      flash[:notice] = "Product was successfully Updated"
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end
  
  def destroy
    if @product.destroy
      flash[:notice] = "Product #{@product.name}, was successfully destroyed"
      redirect_to products_path
    end
  end
  
  
  
  
  
  private
  def find_product
    @product = Product.find(params[:id])
  end
  
  def set_product
    params.require(:product).permit(:name, :description, :price, :brand_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_form.html.erb
<% if @brand.errors.any? %>
<h4 class ="text-center">Oops something went wrong: </h4>
<ul class="text-center">
  <% @brand.errors.full_messages.each do |msg| %>
 <li class ="text-center"><%= msg %></li> 
  <% end %>
  </ul>
<% end %>

<%= simple_form_for @brand, html: {class: 'form-signin'} do |f| %>

  <%= f.input :name, required: true, label: false, placeholder: "Name", autofocus:true %>
  <%= f.submit :submit, class: "btn btn-primary btn-block" %>
  
  
<% end %>
  
<p>
  <%= link_to 'All Brands', brands_path %>
</p>

app/views/brands/edit.html.erb
<h1 class="text-center">Edit Page</h1>
<%= render 'form' %>

app/views/brands/index.html.erb
<h1>Brands list</h1>


<div class ="row">
  <div class ="col-md-12">
    <h3>Brands
    <%= link_to 'New Brand', new_brand_path, class: 'btn btn-primary btn-sm' %>
    </h3>
    <div class="bs-example" data-example-id="condensed-table">
     <table class="table table-condensed"> 
     <thead> 
       <tr> 
       <th>ID</th> 
       <th>Name</th> 
       <th></th> 
       </tr> 
     </thead> 
     <tbody> 
     <% @brands.each do |brand| %>
       <tr> 
       <td><%= brand.id %></td> 
       <td><%= link_to brand.name, brand_path(brand) %></td> 
       <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
       <td><%= link_to 'Delete', brand_path(brand), method: :delete, data: {confirm: "Are you sure?"}, class: 'pull-right' %> </td>
       </tr>   
       <% end %>
     </tbody> 
     </table> 
     </div>
 </div>

app/views/brands/new.html.erb
<h1 class ="text-center">New Brand</h1>
<%= render 'form' %>

app/views/brands/show.html.erb
<h1>Brand</h1>
 <h3><%= @brand.name %></h3>
 <%= link_to 'Back', brands_path %>
 <%= link_to 'Edit', edit_brand_path(@brand) %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Michelada.io', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Brands', brands_path %></li>
        <% if current_user %>
        <li><%= link_to 'New Brand', new_brand_path %></li>
        <li><%= link_to 'New Product', new_product_path %></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <li>Logged in as <strong><%=link_to current_user.email, edit_user_registration_path  %></strong></li>
        
        <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudProducts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class = "container">
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h2>Welcome to Brands-Products application</h2>
  <p>Please Sign in, in order to create new brands</p>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'Brands', brands_path, class: 'btn btn-primary btn-lg' %>
  
</div>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
<h4 class ="text-center">Oops something went wrong: </h4>
<ul class="text-center">
  <% @product.errors.full_messages.each do |msg| %>
 <li class ="text-center"><%= msg %></li> 
  <% end %>
  </ul>
<% end %>

<%= simple_form_for @product, html: {class: 'form-signin'} do |f| %>

  <%= f.input :name, required: true, label: false, placeholder: "Name", autofocus:true %>
  <%= f.input :description, required: true, label: false, placeholder: "Description" %>
  <%= f.input :price, required: true, label: false, placeholder: "Price" %>
  <%= f.collection_select(:brand_id, @brands, :id, :name, prompt: true ) %> 
  <!--%= select("brand", "brand_id", Brand.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }) %> -->
  <%= f.submit :submit, class: "btn btn-primary btn-block" %>
  
  
<% end %>
  
<p>
  <%= link_to 'All Products', products_path %>
</p>

app/views/products/_product.html.erb
<div class ="col-md-3">
    <div class ="img-thumbnail">
      <%= image_tag 'rails.jpg', class: 'img-responsive' %>
      
    </div>
    <div class ="caption">
      <p><strong><%= link_to product.name, product_path(product) %> </strong></p>
      <p>$ <%= product.price %></p>

    </div>
  </div>

app/views/products/edit.html.erb
<h2 class="text-center">Edit Product</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products list</h1>

<div class ="row">
  <div class ="col-md-12">
    <h3>Products
    <%= link_to 'New Product', new_product_path, class: 'btn btn-primary btn-sm' %>
    </h3>
    <div class="bs-example" data-example-id="condensed-table">
     <table class="table table-condensed"> 
     <thead> 
       <tr> 
       <th>ID</th> 
       <th>Name</th> 
       <th></th> 
       </tr> 
     </thead> 
     <tbody> 
     <% @products.each do |product| %>
       <tr> 
       <td><%= product.id %></td> 
       <td><%= link_to product.name, edit_product_path(product) %></td> 
       <td><%= link_to 'Edit', edit_product_path(product) %></td>
       <td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: 'pull-right' %> </td>
       </tr>   
       <% end %>
     </tbody> 
     </table> 
     </div>
 </div>

app/views/products/new.html.erb
<h1 class="text-center">New product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1 class="text-center">show</h1>